[package]
name = "remux-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
autobins = false

[[bin]]
name = "remux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures-util.workspace = true
hostname.workspace = true
portable-pty.workspace = true
remux-protocol = { path = "../protocol" }
rpassword.workspace = true
serde.workspace = true
tokio.workspace = true
rustls.workspace = true
tokio-tungstenite.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
